apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-pod
  template:
    metadata:
      labels:
        app: flask-app-pod
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: ovn-ovs
      hostNetwork: true
      containers:
      - name: flask-app
        image: docker.io/huteqwe123/flask-app:v10
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: flask-app-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000