apiVersion: v1
kind: Pod
metadata:
  name: $(POD_NAME)
  namespace: kube-system
  labels:
    app: $(POD_NAME)
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command: ["/bin/sleep", "infinity"]
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $(POD_NAME)-service
  namespace: kube-system
spec:
  selector:
    app: $(POD_NAME)
  type: ClusterIP
  ports:
  - name: $(POD_NAME)-service
    protocol: TCP
    port: 100
    targetPort: 80